
name: Trading Bot Workflow

on:
  workflow_dispatch:  # Permite iniciar manualmente
  schedule:
    - cron: '30 18 * * 1-5'  # Ejecutar a las 18:30 UTC de lunes a viernes

jobs:
  execute_trades:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Create necessary directories
        run: |
          mkdir -p ./models
          mkdir -p ./data
          
      - name: Execute trading strategy
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python main.py
          
      - name: Commit updated models and logs
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'actions@github.com'
          git add -f ./data ./models trade_log.json || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Update models and trading log [skip ci]"
          git push
          
      - name: Trigger position monitor workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          event-type: start-position-monitor
