name: Position Monitor Workflow

on:
  workflow_dispatch:  # Permite iniciar manualmente
  schedule:
    - cron: '*/5 * * * 1-5'  # Ejecutar cada 5 minutos de lunes a viernes

jobs:
  monitor_positions:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Check market status and monitor positions
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python position_monitor_action.py
          
      - name: Commit position log
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'actions@github.com'
          git add trade_log.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update trading positions [skip ci]"
          git push